spring:
  application:
    name: banking-core
  datasource:
    url: jdbc:postgresql://localhost:5431/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
kafka:
  topic:
    name: banking